config/routes.rb
Rails.application.routes.draw do
  get 'health/check'
  devise_for :users, controllers: { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  root to: "splash#index"

  resources :categories, only: [:index, :new, :create, :show]
  resources :transactions, only: [:new, :create]
  
  get 'health/check', to: 'health#check'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role? :admin
      can :manage, :all
    else
      can :read, :splash
      can :check, HealthController
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_many :group_entities
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_entities

  validates :name, presence: true
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  validates :group_id, presence: true
  validates :entity_id, presence: true
  belongs_to :group
  belongs_to :entity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entities
  has_many :groups
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protected

  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.groups
  end

  def new
    @group = Group.new
    @icon_files = Dir.glob(Rails.root.join('app', 'assets', 'images', 'categories', '*.png')).map do |file_path|
      File.basename(file_path)
    end
  end

  def show
    @category = Group.find(params[:id])
    @transactions = @category.group_entities.order(created_at: :desc)
    @total_amount = 0
    @transactions.each do |item|
      @total_amount += Entity.find(item.entity_id).amount
    end
  end

  def create
    @icon_path = "categories/#{params[:group][:icon]}"
    @category = current_user.groups.create(name: params[:group][:name], icon: @icon_path)
    if @category.save
      redirect_to categories_path, notice: 'Categorie was successfully created'
    else
      redirect_to new_category_path, notice: 'Categories not created!'
    end
  end
end

app/controllers/health_controller.rb
class HealthController < ApplicationController
  skip_before_action :authenticate_user!, only: [:check]
  def check
    render json: { status: 'ok' }
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def show; end

  def new
    @entity = GroupEntity.new
    @category = Group.find(params[:category_id])
  end

  def create
    @category = Group.find(params[:group_entity][:category])
    @entity = current_user.entities.create(name: params[:group_entity][:name], amount: params[:group_entity][:amount])
    @group_entity = @category.group_entities.create(group_id: @category.id, entity_id: @entity.id)

    if @entity.save && @group_entity.save
      redirect_to category_path(@category), notice: 'Transaction created successfully'
    else
      redirect_to new_transaction_path, notice: 'Transaction was not created'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/health_helper.rb
module HealthHelper
end

app/views/categories/_category.html.erb
<div class="category_elmnt">
  <%= link_to category_path(category.id), class: 'no_link' do %>
    <div class="category_info proxima_light_font">
      <div class="category_img_container">
        <%= image_tag category.icon %>
      </div>
      <div class="category_data">
        <h3>
          <%= category.name %>
        </h3>
        <p>
          <%= category.created_at.strftime("%Y-%m-%d") %>
        </p>
      </div>
    </div>
    <div class="category_amout proxima_light_font">
      $<%= number_with_precision(amount, precision: 2) %>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<head>
  <%= stylesheet_link_tag "categories" %>
</head>
<body>
  <div class="categories_container">
    <div class="transaction_header proxima_bold_font">
      <div>
        <%= link_to "n", categories_path, class: "simbols_font" %>
      </div>
      <div class="categories_title">
        CATEGORIES
      </div>
      <div>
        <%= link_to 'L', categories_path, class: "simbols_font" %>
      </div>
    </div>
    <div class="fill_container">
      <% @categories.each do |item| %>
        <% @regs = item.group_entities %>
        <% @total_category = 0 %>
        <% @regs.each do |reg| %>
          <% @total_category += Entity.find(reg.entity_id).amount %>
        <% end %>
        <%= render partial: 'categories/category', locals: { category: item, amount: @total_category } %>
      <% end %>
    </div>
    <div class="action_btn proxima_light_font">
      <%= link_to 'Create New Category', new_category_path %>
    </div>
  </div>
</body>

app/views/categories/new.html.erb
<head>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <%= stylesheet_link_tag "categories" %>
</head>
<body>
  <%= form_with(model: @group, url: categories_path, method: :post) do |form| %>
    <div class="transaction_header proxima_bold_font">
      <div>
        <%= link_to "h", categories_path, class: "simbols_font" %>
      </div>
      <div class="categories_title">
        NEW CATEGORY
      </div>
      <div class="save_btn">
        <%= form.submit 'Save' %>
      </div>
    </div>

    <div class="category_input_container">
      <%= form.text_field :name, placeholder: "Category Name", class: "new_category_input" %>
    </div>

    <div class="category_icon_select">
      <%= form.collection_select :icon, @icon_files, :itself, ->(file) { file.split('.').first }, { prompt: 'Select an icon' }, class: 'select-field' %>
    </div>
  <% end %>
  <div id="selected-icon-preview" class="category_new_icon"></div>
</body>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var selectField = document.querySelector('.select-field');
    var previewContainer = document.getElementById('selected-icon-preview');

    if (selectField) {
      selectField.addEventListener('change', function() {
        var selectedIcon = this.value;
        console.log(selectedIcon);

        previewContainer.innerHTML = '';

        if (selectedIcon) {
          var img = document.createElement('img');
          img.src = '/assets/categories/' + selectedIcon;
          img.alt = selectedIcon;
          previewContainer.appendChild(img);
        }
      });
    }
  });
</script>

app/views/categories/show.html.erb
<head>
  <%= stylesheet_link_tag "categories" %>
</head>
<body>
  <div class="transaction_header proxima_bold_font">
    <div>
      <%= link_to "h", categories_path, class: "simbols_font" %>
    </div>
    <div class="categories_title">
      TRANSACTIONS
    </div>
    <div>
      <%= link_to 'L', categories_path, class: "simbols_font" %>
    </div>
  </div>
  <div class="transaction_total proxima_bold_font">
    <p>Total amout</p>
    <h3> $<%= @total_amount.round(2) %></h3>
  </div>
  <div class="fill_container">
    <% @transactions.each do |item|  %>
      <%= render partial: 'transactions/transaction', locals: { transaction: item } %>
    <% end %>
  </div>
  <div class="action_btn proxima_light_font">
    <%= link_to 'Add New Transaction', new_transaction_path(category_id: @category.id) %>
  </div>
</body>

app/views/health/check.html.erb
<h1>Health#check</h1>
<p>Find me in app/views/health/check.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinancialLife</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "styles" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hedvig+Letters+Sans&family=Montserrat:wght@300&family=Noto+Sans+Symbols+2&family=Satisfy&display=swap" rel="stylesheet">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div class="splash">
  <div class="splash_title">
    Financial Life!
  </div>
  <div class="splash_btns">
    <div class="splash_login proxima_light_font">
      <%= link_to 'LOG IN', new_user_session_path %>
    </div>
    <div class="splash_signup proxima_light_font">
      <%= link_to 'SIGN UP', new_user_registration_path %>
    </div>
  </div>
</div>

app/views/transactions/_transaction.html.erb
<div class="transaction_elmnt proxima_light_font">
  <div class="transaction_data">
    <% @myTrans = Entity.find(transaction.entity_id) %>
    <h3>
      <%= @myTrans.name %>
    </h3>
    <p>
      Transaction Nº<%= @myTrans.id %>
    </p>
    <p>
      <%= @myTrans.created_at.strftime("%Y-%m-%d") %>
    </p>
  </div>
  <div>
    <h3>
      $<%= @myTrans.amount.round(2) %>
    </h3>
  </div>
</div>

app/views/transactions/new.html.erb
<head>
  <%= stylesheet_link_tag "categories" %>
</head>
<body>
  <div>
    <%= form_with(model: @entity, url: transactions_path, method: :post) do |form| %>
      <div class="transaction_header proxima_bold_font">
        <div>
          <%= link_to "h", category_path(@category), class: "simbols_font" %>
        </div>
        <div class="categories_title">
          NEW TRANSACTION
        </div>
        <div class="save_btn">
          <%= form.submit 'Save' %>
        </div>
      </div>
      <div class="new_transaction_container">
        <div>
          <%= form.text_field :name, placeholder: "name", class: "new_transaction_input" %>
        </div>

        <div>
          <%= form.number_field :amount, step: '0.01', placeholder: "amount", class: "new_transaction_input" %>
        </div>

        <div>
          <%= form.collection_select :category, Group.all, :id, :name, { prompt: 'Select an option' }, placeholder:"category", class: 'select-field' %>
        </div>
      </div>
    <% end %>
  </div>  
</body>